/* **************************************************************************************************
 *
 *Module : ULTRASONIC
 *
 * Name  :  ultra.c
 *
 * Author: Mohamed Faryed
 *
 * Description: Source file of ultrasonic driver for AVR
 *
 * Created on: March 3, 2022
 *
 ****************************************************************************************************/

#include <util/delay.h>
#include "ultra.h"
#include "../../mcal/icu/icu.h"
#include "../../mcal/gpio/gpio.h"

/********************************************************************************************************
 *                               Static Global variable                                                 *
 ********************************************************************************************************/
static volatile uint8 g_edgeCount = 0;
static volatile uint16 g_timeDistance = 0;

/********************************************************************************************************
 *                              Static Function                                                         *
 ********************************************************************************************************/


/*
 *  Description:
 *               This is the call back function called by the ICU driver.
 *               This is used to calculate the high time (pulse time) generated by
 *               the ultrasonic sensor.
 ********************************************************************************************************/

 static void Ultrasonic_edgeProcessing (void)
{
	++g_edgeCount;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeDistance = Icu_getInputCaptureValue();
		/* Detect rising edge */
		g_edgeCount=0;
		Icu_setEdgeDetectionType(RISING);

	}
}

 /********************************************************************************************************
  *                               Function Definition                                                    *
  ********************************************************************************************************/


 /*
  *  Description:
  *               give the require input for ICU
  *               determine which pin will be trigger signal
  *               start signal to calculate time distance
  ********************************************************************************************************/
 void Ultrasonic_init(void)
{
	Icu_ConfigType s_ultra_config={F_CPU_8,RISING};
	GPIO_setupPinDirection(ECHO_PORT,ECHO_PIN,PIN_INPUT);
	GPIO_setupPinDirection(TRIGER_PORT,TRIGER_PIN,PIN_OUTPUT);

	Icu_init(&s_ultra_config);
	Icu_setCallBack(Ultrasonic_edgeProcessing);

}



 /*
  *  Description:
  *               start signal to calculate time distance
  ********************************************************************************************************/
 void Ultrasonic_Trigger(void)
 {

	GPIO_writePin(TRIGER_PORT,TRIGER_PIN,LOGIC_HIGH);
	_delay_ms(1);
	GPIO_writePin(TRIGER_PORT,TRIGER_PIN,LOGIC_LOW);

 }



 /*
  *  Description:
  *                calculate the distance and return the value
  ********************************************************************************************************/
uint16 Ultrasonic_readDistance(void)
{
	Icu_clearTimerValue();
	Ultrasonic_Trigger();
	float time = ((float)g_timeDistance/F_CPU);
	uint16 value = (uint16)((float)(34000*time)/2);
	return value;
}
